services:
  stats-server:
    build:
      context: .
      dockerfile: ewm-stats/stats/Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm_stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_pass

  stats-db:
    image: postgres:16.1
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=ewm_stats
      - POSTGRES_USER=stats_user
      - POSTGRES_PASSWORD=stats_pass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-service:
    build:
      context: .
      dockerfile: ewm-service/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:5432/ewm_service
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass
      - STATS_SERVICE_URL=http://stats-server:9090

  ewm-db:
    image: postgres:16.1
    container_name: postgres_ewm
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_DB=ewm_service
      - POSTGRES_USER=ewm_user
      - POSTGRES_PASSWORD=ewm_pass
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
